export const mockVariantProducts = [
  {
    id: 'sku-001',
    name: 'Wireless Mouse - Compact',
    image: {
      url: 'https://storeframework.vtexassets.com/arquivos/ids/190902/unsplash-magic-mouse.jpg?v=1759260622',
      alternateName: 'Wireless Mouse Small',
    },
    inventory: 50,
    availability: 'inStock',
    price: 29.99,
    listPrice: 39.99,
    priceWithTaxes: 32.99,
    listPriceWithTaxes: 43.99,
    specifications: {
      size: 'Small',
      color: 'White',
      material: 'Plastic',
      packsize: '1 unit',
    },
    selectedCount: 0,
    offers: {
      highPrice: 39.99,
      lowPrice: 29.99,
      lowPriceWithTaxes: 32.99,
      offerCount: 1,
      priceCurrency: 'USD',
      offers: [
        {
          listPrice: 39.99,
          listPriceWithTaxes: 43.99,
          sellingPrice: 29.99,
          priceCurrency: 'USD',
          price: 29.99,
          priceWithTaxes: 32.99,
          priceValidUntil: '2025-12-31',
          itemCondition: 'NewCondition',
          availability: 'https://schema.org/InStock',
          quantity: 50,
        },
      ],
    },
  },
  {
    id: 'sku-002',
    name: 'Wireless Mouse - Standard',
    image: {
      url: 'https://storeframework.vtexassets.com/arquivos/ids/190932/mouse-black.jpg?v=1759260622',
      alternateName: 'Wireless Mouse Medium',
    },
    inventory: 75,
    availability: 'inStock',
    price: 29.99,
    listPrice: 39.99,
    priceWithTaxes: 32.99,
    listPriceWithTaxes: 43.99,
    specifications: {
      size: 'Medium',
      color: 'Black',
      material: 'Plastic',
      packsize: '1 unit',
    },
    selectedCount: 0,
    offers: {
      highPrice: 39.99,
      lowPrice: 29.99,
      lowPriceWithTaxes: 32.99,
      offerCount: 1,
      priceCurrency: 'USD',
      offers: [
        {
          listPrice: 39.99,
          listPriceWithTaxes: 43.99,
          sellingPrice: 29.99,
          priceCurrency: 'USD',
          price: 29.99,
          priceWithTaxes: 32.99,
          priceValidUntil: '2025-12-31',
          itemCondition: 'NewCondition',
          availability: 'https://schema.org/InStock',
          quantity: 75,
        },
      ],
    },
  },
  {
    id: 'sku-003',
    name: 'Wireless Mouse - Ergonomic',
    image: {
      url: 'https://storeframework.vtexassets.com/arquivos/ids/190935/magic-side.jpg?v=1759260622',
      alternateName: 'Wireless Mouse Large',
    },
    inventory: 60,
    availability: 'inStock',
    price: 29.99,
    listPrice: 39.99,
    priceWithTaxes: 32.99,
    listPriceWithTaxes: 43.99,
    specifications: {
      size: 'Large',
      color: 'White',
      material: 'Plastic',
      packsize: '1 unit',
    },
    selectedCount: 0,
    offers: {
      highPrice: 39.99,
      lowPrice: 29.99,
      lowPriceWithTaxes: 32.99,
      offerCount: 1,
      priceCurrency: 'USD',
      offers: [
        {
          listPrice: 39.99,
          listPriceWithTaxes: 43.99,
          sellingPrice: 29.99,
          priceCurrency: 'USD',
          price: 29.99,
          priceWithTaxes: 32.99,
          priceValidUntil: '2025-12-31',
          itemCondition: 'NewCondition',
          availability: 'https://schema.org/InStock',
          quantity: 60,
        },
      ],
    },
  },
  {
    id: 'sku-005',
    name: 'Wireless Mouse - Ergonomic',
    image: {
      url: 'https://storeframework.vtexassets.com/arquivos/ids/190933/Magic_Mouse_Black_Pure_Top_Screen__USEN_1.png?v=1759260622',
      alternateName: 'Wireless Mouse XX-Large',
    },
    inventory: 0,
    availability: 'outOfStock',
    price: 31.99,
    listPrice: 39.99,
    priceWithTaxes: 35.19,
    listPriceWithTaxes: 43.99,
    specifications: {
      size: 'Medium',
      color: 'Black',
      material: 'Plastic',
      packsize: '1 unit',
    },
    selectedCount: 0,
    offers: {
      highPrice: 39.99,
      lowPrice: 31.99,
      lowPriceWithTaxes: 35.19,
      offerCount: 1,
      priceCurrency: 'USD',
      offers: [
        {
          listPrice: 39.99,
          listPriceWithTaxes: 43.99,
          sellingPrice: 31.99,
          priceCurrency: 'USD',
          price: 31.99,
          priceWithTaxes: 35.19,
          priceValidUntil: '2025-12-31',
          itemCondition: 'NewCondition',
          availability: 'https://schema.org/OutOfStock',
          quantity: 0,
        },
      ],
    },
  },
]
