name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: wait-for-netflify-preview
        with:
          site_name: 'elated-hoover-5c29bf'
          max_timeout: 1800
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Fetch navigation.json
        uses: wei/curl@v1
        with:
          args: -o src/tests/cypress/fixtures/navigation.json https://developers.vtex.com/navigation.json
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_baseUrl: ${{ steps.wait-for-netflify-preview.outputs.url }}
